### ISSUE TITLE
Distorted view with Looking Glass Portrait LGP and Slicer 3D + Extention

### ISSUE THREAD

**Issue by basecore** [KitwareMedical/SlicerLookingGlass#17]
With Slicer 3D (4.13) and the new LGP I get a distorted view of the volume rendering. 
Unfortunately, pushing or pulling the focal plane backward or forward doesn’t help.
The scaling of my display setting is set to 100%. Resolution is 1536x2048.
In the Looking Glass Factory discord group it seems that the same issue happens in ParaView.

My Setup:
- Windows 10 
- Slicer 3D (4.13)
- latest Slicer Looking Glass Extention
- Looking Glass Portait (the horizontal one with 1536x2048)
- HoloPlay Service 1.2.2

![photo_2021-08-19_08-50-24](https://user-images.githubusercontent.com/5770205/130022438-99e75063-95c1-4ed0-8a37-40179b577f38.jpg)

**Comment by egipane** [comment]
I have the same issue with the adjustment of the focal plane. The buttons do not change anything.

**Comment by mikeridley** [comment]
Same issue.

**Comment by curtislisle** [comment]
My LGP behaves similarly.  When the 3D camera is moved very close to an object, the LGP rendering exhibits less double imaging, but the aspect ratio is always stretched vertically.  I think this extension was developed using an earlier,  LG model with a wider aspect ratio. I am not able to adjust the focal plane either.  This is a neat prototype application, and it will be more usable when it is brought up to date with the new LGP hardware and with a few issues fixed.

**Comment by pieper** [comment]
Yes, I'm having the same issue here.  @jcfr, @samuelgerber or @sjh26 do you have any suggestions?

![image](https://user-images.githubusercontent.com/126077/149635577-0fdc7eb0-efb1-4e1a-a1eb-d5d228d37453.png)

**Comment by LucasGandel** [comment]
I think this is related to [#23](https://github.com/Kitware/LookingGlassVTKModule/pull/23). The aspect ratio is wrong with portrait devices.

Unfortunately I could not find the right fix yet, the proposed solution seems to cause issues with landscape devices.
