### ISSUE TITLE
Volume rendering does not show up

### ISSUE THREAD

**Issue by cpinter** [KitwareMedical/SlicerLookingGlass#22]
I tried Looking Glass today with Slicer 5.0.2, and noticed that volume rendering does not show up in the Looking Glass view. If I show slice intersections in 3D and the volume rendering, then it shows in the regular 3D view, but in the device only the slice intersections show up.

This seems to be the same issue that we noticed with virtual reality, see https://github.com/KitwareMedical/SlicerVirtualReality/issues/91

**Comment by jcfr** [comment]
Closing. This is likely fixed in Slicer Preview (v5.1) through the integration of https://github.com/Slicer/Slicer/pull/6584

**Comment by cpinter** [comment]
Excellent, thank you!
